blank_issues_enabled: true
contact_links:
    - name: "ğŸ“• Docs: Upgrade from Legacy CSF"
      url: "https://docs.configserver.dev/install/update/v1500-to-newer/"
      about: "For users who want to upgrade from discontinued version of CSF to our version."
    - name: "ğŸ“™ Docs: Installation Guide"
      url: "https://docs.configserver.dev/install/install/"
      about: "Full documentation for installing CSF."
    - name: "ğŸ’¬ Chat: Disord Server"
      url: "https://discord.configserver.dev"
      about: "Talk to our community on Discord."
    - name: "âš™ï¸ Status: Services"
      url: "https://status.configserver.dev"
      about: "View current system status."