# #
#   Mkdocs Config
#
#   @notes            this documentation requires the following plugins to be installed:
#                         pip install mkdocs
#                         pip install mkdocs-material
#                         pip install mike
#                         pip install mkdocs-git-committers-plugin-2
#                         pip install mkdocs-encryptcontent-plugin
#                         pip install mkdocs-embed-external-markdown
#                         pip install mkdocs-redirects mkdocs-glightbox pymdown-extensions mkdocs-git-revision-date-localized-plugin mkdocs-git-authors-plugin mkdocs-link-embeds-plugin
#                         cd docs
#                         mkdocs build
#
#   @update           use the following commands to update mkdocs and the mkdocs-material theme:
#                         pip install --upgrade mkdocs
#                         pip install --upgrade --force-reinstall mkdocs-material
# #

site_name: !!python/object/apply:os.getenv ["DOCS_NAME", "ConfigServer Security and Firewall"]
repo_url: https://github.com/aetherinox/csf-firewall
repo_name: Aetherinox/csf-firewall
edit_uri: edit/main/docs/docs/
site_author: Aetherinox
site_url: 'https://aetherinox.github.io/csf-firewall/'

# #
#   Section â€º Markdown Extensions
# #

markdown_extensions:
    - material.extensions.preview:
        configurations:
            - targets:
                include:
                - about/changelog.md
                - install/*
                - insiders/*
                - usage/*
                - advanced/*
    - pymdownx.critic
    - markdown.extensions.extra
    - toc:
          permalink: true
    - abbr
    - admonition
    - attr_list
    - pymdownx.magiclink:
          normalize_issue_symbols: true
          repo_url_shorthand: true
          user: Aetherinox
          repo: csf-firewall
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
          options:
              custom_icons:
                  - material/overrides/.icons
    - md_in_html
    - def_list
    - footnotes
    - tables
    - pymdownx.inlinehilite
    - pymdownx.betterem:
          smart_enable: all
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.highlight:
          use_pygments: true
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed:
          alternate_style: true
          combine_header_slug: true
          slugify: !!python/object/apply:pymdownx.slugs.slugify
              kwds:
                  case: lower
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.tilde
    - pymdownx.blocks.html
    - pymdownx.details
    - pymdownx.keys
    - pymdownx.snippets:
          auto_append:
              - docs/includes/abbreviations.md
          url_download: true
    - pymdownx.arithmatex:
          generic: true

# #
#   Section â€º Theme
# #

theme:
    highlightjs: true
    hljs_languages:
        - yaml
        - yml
        - rust
        - markdown
        - json
        - batch
        - typescript
        - javascript
        - lua
        - ini
        - python
        - bash
        - shell
    icon:
        admonition:
            csf1: aetherx/axs/csf-logo-1
        note: fontawesome/solid/note-sticky
        abstract: fontawesome/solid/book
        info: fontawesome/solid/circle-info
        tip: fontawesome/solid/bullhorn
        success: fontawesome/solid/check
        question: fontawesome/solid/circle-question
        warning: fontawesome/solid/triangle-exclamation
        failure: fontawesome/solid/bomb
        danger: fontawesome/solid/skull
        bug: fontawesome/solid/robot
        example: fontawesome/solid/flask
        quote: fontawesome/solid/quote-left
        annotation: material/arrow-right-circle
        hi: aetherx/axs/clock
        csf1: aetherx/axs/csf-logo-1
        csf2: aetherx/axs/csf-logo-2
        tag:
            html: fontawesome/brands/html5
            js: fontawesome/brands/js
            css:  fontawesome/brands/css3
        repo: fontawesome/brands/git-alt
    name: material
    custom_dir: material/overrides
    palette:
        # Palette toggle for light mode
        - scheme: default
          primary: custom
          accent: indigo
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode

        # Palette toggle for dark mode
        - scheme: main
          primary: custom
          accent: custom
          toggle:
              icon: material/brightness-4
              name: Switch to light mode
    font:
        text: Roboto
        code: Roboto Mono
    favicon: assets/favicon.png
    icon:
        logo: /aetherx/axs/csf-logo-1
    features:
        - announce.dismiss
        - toc.follow
        - content.action.edit
        - content.action.view
        - content.tooltips
        - search.highlight
        - search.share
        - search.suggest
        - content.code.annotate
        - content.code.select
        - content.code.copy
        - navigation.tabs
        - navigation.sections
        - navigation.footer
        - navigation.indexes
        - navigation.instant
        - navigation.instant.progress
        - navigation.instant.prefetch
        - navigation.instant.preview
        - navigation.tracking
        - navigation.path
        - navigation.top
# #
#   Section â€º Hooks
# #

hooks:
    - material/overrides/hooks/shortcodes.py
    - material/overrides/hooks/translations.py

# #
#   Section â€º Extra â€º CSS
# #

extra_css:
    - stylesheets/extra.css?v1.000
  # - stylesheets/all.min.css?v7.000


# #
#   Section â€º Extra â€º Javascript
# #

extra_javascript:
    - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
    - javascripts/tablesort.js
    - javascripts/all.js?v7.000
    - javascripts/sponsors.js

# #
#   Section â€º Extras
#   
#   extra:
#     status:         requires you to add new status to extras.css file
#                     pre-defined status:
#                         - new
#                         - deprecated
# #

extra:
    status:
        important: Important
        new: New Addition
    social:
        - icon: aetherx/axs/download
          link: https://download.configserver.dev
          name: Download CSF
        - icon: aetherx/axs/block-brick-fire
          link: https://blocklist.configserver.dev
          name: Service â€º Blocklists
        - icon: aetherx/axb/github-alt
          link: https://tickets.configserver.dev
          name: Submit Issue / Ticket
        - icon: fontawesome/brands/github
          link: https://github.com/Aetherinox/csf-firewall
          name: View Github Repo
        - icon: aetherx/axb/discord
          link: https://discord.configserver.dev
          name: Discord
        - icon: aetherx/axs/heart
          link: https://buymeacoffee.com/aetherinox
          name: Sponsor
    tags:
        HTML5: html
        JavaScript: js
        CSS: css
    generator: false
    version:
        default: latest
        provider: mike
        alias: true
    consent:
        title: Cookie Consent
        description: >-
          We use cookies to recognize your repeated visits and preferences, as well
          as to measure the effectiveness of our documentation and whether users
          find what they're searching for. With your consent, you're helping us to
          make our documentation better.

# #
#   Section â€º Navigation
# #

nav:
    - Home: 'home.md'
    - About:
          - Introduction: 'about/csf.md'
          - Contributing: 'about/contributing.md'
          - License: 'about/license.md'
          - Privacy: 'about/privacy.md'
          - Wiki:
                - Conventions: 'about/conventions.md'
                - Tags: 'about/tags.md'
    - Install:
          - Dependencies: 'install/dependencies.md'
          - Download: 'install/download.md'
          - Diagnostic Tests: 'install/tests.md'
          - Install: 'install/install.md'
          - Start Services: 'install/services.md'
          - Enable Web Interface: 'install/webui.md'
          - Uninstall: 'install/uninstall.md'
          - Update:
                - v14.x to v15.x: 'install/update/v14-to-v15.md'
                - v15.x to Newer: 'install/update/v15-to-newer.md'
          - Integrations:
                - Authentik: 'install/integrations/authentik.md'
                - Docker: 'install/integrations/docker.md'
                - Traefik: 'install/integrations/traefik.md'
    - Usage:
          - Getting Started: 'usage/getting-started.md'
          - Configuration: 'usage/configuration.md'
          - Pre & Post Scripts: 'usage/prepost.md'
          - Blocklists: 'usage/blocklists.md'
          - Ipsets: 'usage/ipset.md'
          - Geographical Blocks: 'usage/geoip.md'
          - Troubleshooting:
                - usage/troubleshooting/index.md
                - Cyberpanel: usage/troubleshooting/cyberpanel.md
                - Dependencies: usage/troubleshooting/dependencies.md
                - Web Interface: usage/troubleshooting/webui.md
          - Cheatsheet:
                - Home: 'usage/cheatsheet/home.md'
                - Commands: 'usage/cheatsheet/commands.md'
                - Control Panels: 'usage/cheatsheet/control_panels.md'
                - Example Configs: 'usage/cheatsheet/conf.md'
                - Ports: 'usage/cheatsheet/ports.md'
                - Structure: 'usage/cheatsheet/structure.md'
    - Advanced:
            - advanced/index.md
            - CSGet: advanced/csget/index.md
    - Services:
            - services/index.md
            - blocklist.configserver.dev: 'services/blocklist.configserver.md'
            - download.configserver.dev: 'services/download.configserver.md'
            - get.configserver.dev: 'services/get.configserver.md'
    - Insiders:
          - About: insiders/about.md
          - Payments and Billing: insiders/payments_and_billing.md
          - Join Insiders: insiders/join.md
          - Our Sponsors: insiders/sponsors.md
          - Using Insiders:
              - Setup: insiders/setup.md
              - Disable: insiders/disable.md
    - Changelog: 'about/changelog.md'
    - Blog:
        - blog/index.md
    - Discord: 'https://discord.configserver.dev'
    - Create Ticket: 'https://tickets.configserver.dev'
    - Sponsor: 'https://buymeacoffee.com/aetherinox'

# #
#   Section â€º Plugins
# #

plugins:
    - search:
          separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
    - tags:
          tags_file: about/tags.md
    - group:
          plugins:
              - optimize
              - minify
    - git-committers:
          repository: Aetherinox/csf-firewall
          docs_path: docs/docs/
          branch: main
          token: !!python/object/apply:os.getenv [GH_TOKEN, "NULL"]
    - blog:
          authors: true
          authors_file: "{blog}/.authors.yml"
          blog_dir: blog
          blog_toc: true
          post_dir: "{blog}/posts"
          post_date_format: full
          post_url_date_format: yyyy
          post_url_format: "{date}/{slug}"
          post_url_max_categories: 2
          post_slugify: !!python/object/apply:pymdownx.slugs.slugify
              kwds:
                  case: lower
          post_slugify_separator: "-"
          post_excerpt_max_authors: 2
          post_readtime: true
          post_readtime_words_per_minute: 265
          archive: true
          archive_name: Archive
          archive_date_format: MMMM yyyy
          archive_url_date_format: yyyy
          archive_url_format: "{date}"
          archive_toc: true
          categories: true
          categories_name: Categories
          categories_url_format: "{slug}"
    - encryptcontent:
          title_prefix: '[ðŸ”’]'
          summary: 'Restricted Access'
          placeholder: 'Authentication Code'
          placeholder_user: User
          password_button: True
          html_template_path: "material/templates/decrypt-form.tpl.html"
          js_template_path: "material/templates//decrypt-contents.tpl.js"
          form_class: 'md-content__inner md-typeset'
          input_class: 'md-input'
          button_class: 'md-button md-button--primary'
          password_button_text: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512" fill="currentColor" width="15px" height="15px"><path d="M432 64c-44.2 0-80 35.8-80 80v48h32c35.3 0 64 28.7 64 64V448c0 35.3-28.7 64-64 64H64c-35.3 0-64-28.7-64-64V256c0-35.3 28.7-64 64-64H288V144C288 64.5 352.5 0 432 0s144 64.5 144 144v48c0 17.7-14.3 32-32 32s-32-14.3-32-32V144c0-44.2-35.8-80-80-80zM256 384c17.7 0 32-14.3 32-32s-14.3-32-32-32H192c-17.7 0-32 14.3-32 32s14.3 32 32 32h64z"></path></svg>'
          decryption_failure_message: 'Authentication not correct.'
          encryption_info_message: "This information is restricted to certain users with access."
          search_index: 'dynamically'
          webcrypto: true
          threshold_warning_min_entropy: 60
          password_inventory:
              sponsor:
                  - !!python/object/apply:os.getenv [DOCS_SECRET_SPONSOR, "NULL"]
              developer:
                  - !!python/object/apply:os.getenv [DOCS_SECRET_DEVELOPER, "NULL"]
    - git-revision-date-localized:
          type: timeago
          enabled: true
    - git-authors:
          show_contribution: true
          sort_authors_by: name
          exclude:
              - index.md
          enabled: true
    - glightbox:
          touchNavigation: true
          loop: false
          effect: zoom
          slide_effect: slide
          width: 100%
          height: auto
          zoomable: true
          draggable: false
          skip_classes:
              - custom-skip-class-name
          auto_caption: false
          caption_position: bottom
          background: black
          shadow: false
    - mike:
          alias_type: symlink
          redirect_template: null
          deploy_prefix: ''
          canonical_version: null
          version_selector: true
          css_dir: css
          javascript_dir: js
    - redirects:
          redirect_maps:
              docs/settings/summary.md: settings/summary.md
    - external-markdown
    # - macros

copyright: >
  Copyright &copy; 2025 - Aetherinox
